export const city = ['시/도 선택', '서울특별시', '인천광역시', '대전광역시', '광주광역시', '대구광역시', '울산광역시', '부산광역시', '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도', '경상남도', '제주도'];
export const area = [
  ['구/군 선택'],
  ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
  ['계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '중구', '강화군', '옹진군'],
  ['대덕구', '동구', '서구', '유성구', '중구'],
  ['광산구', '남구', '동구', '북구', '서구'],
  ['남구', '달서구', '동구', '북구', '서구', '수성구', '중구', '달성군'],
  ['남구', '동구', '북구', '중구', '울주군'],
  ['강서구', '금정구', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구', '서구', '수영구', '연제구', '영도구', '중구', '해운대구', '기장군'],
  ['고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시', '동두천시', '부천시', '성남시', '수원시', '시흥시', '안산시', '안성시', '안양시', '양주시', '오산시', '용인시', '의왕시', '의정부시', '이천시', '파주시', '평택시', '포천시', '하남시', '화성시', '가평군', '양평군', '여주군', '연천군'],
  ['강릉시', '동해시', '삼척시', '속초시', '원주시', '춘천시', '태백시', '고성군', '양구군', '양양군', '영월군', '인제군', '정선군', '철원군', '평창군', '홍천군', '화천군', '횡성군'],
  ['제천시', '청주시', '충주시', '괴산군', '단양군', '보은군', '영동군', '옥천군', '음성군', '증평군', '진천군', '청원군'],
  ['계룡시', '공주시', '논산시', '보령시', '서산시', '아산시', '천안시', '금산군', '당진군', '부여군', '서천군', '연기군', '예산군', '청양군', '태안군', '홍성군'],
  ['군산시', '김제시', '남원시', '익산시', '전주시', '정읍시', '고창군', '무주군', '부안군', '순창군', '완주군', '임실군', '장수군', '진안군'],
  ['광양시', '나주시', '목포시', '순천시', '여수시', '강진군', '고흥군', '곡성군', '구례군', '담양군', '무안군', '보성군', '신안군', '영광군', '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군'],
  ['경산시', '경주시', '구미시', '김천시', '문경시', '상주시', '안동시', '영주시', '영천시', '포항시', '고령군', '군위군', '봉화군', '성주군', '영덕군', '영양군', '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '칠곡군'],
  ['거제시', '김해시', '마산시', '밀양시', '사천시', '양산시', '진주시', '진해시', '창원시', '통영시', '거창군', '고성군', '남해군', '산청군', '의령군', '창녕군', '하동군', '함안군', '함양군', '합천군'],
  ['서귀포시', '제주시', '남제주군', '북제주군']
];
export const blog = ['유튜브', '인스타', '블로그', '트위치'];
export const testData = [
  {
    picture_url: 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=701&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '257',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 4,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '1566',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 22,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1542728498-09c6a1af7cb9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '2653',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 23,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=633&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '9666',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 48,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1549068106-b024baf5062d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '9666',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 48,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1545996124-0501ebae84d0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '9666',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 48,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1545912453-db258ca9b7b7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '9666',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 48,
  },
  {
    picture_url: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=633&q=80',
    title: '[인스타방문형] 연남 카세트',
    text: '취미발레는 인어스발레스튜디오에서!',
    influencers_count: '9666',
    requests_count: '5',
    tags: '#inflai #advertise',
    INF_ID: 48,
  },
  /* {
      profile_picture_url: 'https://images.unsplash.com/photo-1549068106-b024baf5062d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
      username: 'Lucas',
      name: '박이솔',
      followers_count: '15254',
      INF_ID: 49,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1545996124-0501ebae84d0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80',
      username: 'Amir',
      name: '김진후',
      followers_count: '26325',
      INF_ID: 54,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1545912453-db258ca9b7b7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
      username: 'Valerie',
      name: '유서후',
      followers_count: '36235',
      INF_ID: 1,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1569124589354-615739ae007b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
      username: 'Ilinerwise',
      name: '문희원',
      followers_count: '750',
      INF_ID: 2,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1545167622-3a6ac756afa4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=656&q=80',
      username: 'Reza Biazar',
      name: '황찬세',
      followers_count: '150213',
      INF_ID: 3,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1541647376583-8934aaf3448a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
      username: 'Harishan Kobalasingam',
      name: '김예준',
      followers_count: '3533',
      INF_ID: 6,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1565260524775-7e9b536fba2f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
      username: 'Pantian Punpuang',
      name: '박현우',
      followers_count: '65235',
      INF_ID: 5,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1547624643-3bf761b09502?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
      username: 'Sebastian Hemetsberger',
      name: '김지호',
      followers_count: '23633',
      INF_ID: 7,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1546820389-44d77e1f3b31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80',
      username: 'Jake_Fagan',
      name: '최준우',
      followers_count: '12856',
      INF_ID: 8,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?ixlib=rb-1.2.1&auto=format&fit=crop&w=564&q=80',
      username: 'Arshd_Khad',
      name: '문시우',
      followers_count: '19652',
      INF_ID: 9,
    },
    {
      profile_picture_url: 'https://images.unsplash.com/photo-1530512728528-123933595874?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
      username: 'Roberto_Delgado',
      name: '김민준',
      followers_count: '26542',
      INF_ID: 10,
    }, */
];
export const classification = [{ value: '1', text: '국내사업자' }, { value: '2', text: '해외사업자' }];
export const jobType = [{ value: '1', text: '일반' }, { value: '2', text: '에이전시' }, { value: '3', text: '소상공인' }];
export const testText = 'test';
export const Colors = {
  white: '#ffffff',
  blue: '#093c5e',
  blue2: '#409CFF',
  blue2Back: '#DDEFFF',
  blue2Hover: '#467fbd',
  orange: '#FF835D',
  orangeBack: '#FFEAE6',
  skyBlue: '#4376e8',
  aqua: '#23c9cf',
  red: '#fa4616',
  black: '#333',
  grey: '#dfe2e8',
  grey2: '#999999',
  grey3: '#f5f6f7',
  grey4: '#eaeaea',
  grey5: '#a8a8a8',
  grey6: '#efefef',
  grey7: '#e9e9e9',
  grey8: '#ddd',
  green: '#24d024',
  pink: '#eb128c',
  pink2: '#fec1e3',
  pink3: '#f971b8',
};
export const campaignSteps = [{ value: '1', text: '리뷰어 신청' }, { value: '2', text: '리뷰어 발표' }, { value: '3', text: '리뷰등록' }, { value: '4', text: '베스트발표' }];

export const AdvertiseTypes = {
  mainType: ['지역', '제품', '서비스', '가치단'],
  subType: [
    ['맛집', '뷰티', '숙박', '문화', '기타'],
    ['생활', '유아동', '뷰티', '디지털', '패션', '도서', '식품'],
    ['쇼핑몰', '웹서비스', '이벤트', '교육'],
    []
  ],
};
